const top100Locations = [
    { label: 'Recife', country: 'Brasil' },
    { label: 'Olinda', country: 'Brasil' },
    { label: 'Paulista', country: 'Brasil' },
    { label: 'Praia de Boa Viagem, Recife', country: 'Brasil' },
    { label: 'Marco Zero, Recife', country: 'Brasil' },
    { label: 'Teatro de Santa Isabel, Recife', country: 'Brasil' },
    { label: 'Museu do Frevo, Recife', country: 'Brasil' },
    { label: 'Praça do Carmo, Olinda', country: 'Brasil' },
    { label: 'Igreja da Sé, Olinda', country: 'Brasil' },
    { label: 'Alto da Sé, Olinda', country: 'Brasil' },
    { label: 'Convento de São Francisco, Olinda', country: 'Brasil' },
    { label: 'Praça de Maranguape, Paulista', country: 'Brasil' },
    { label: 'Praia do Janga, Paulista', country: 'Brasil' },
    { label: 'Igreja de Nossa Senhora do Rosário, Paulista', country: 'Brasil' },
    { label: 'Parque Dona Lindu, Recife', country: 'Brasil' },
    { label: 'Shopping Recife, Recife', country: 'Brasil' },
    { label: 'Parque das Esculturas, Recife', country: 'Brasil' },
    { label: 'Barracão do Maracatu, Recife', country: 'Brasil' },
    { label: 'Pátio de São Pedro, Recife', country: 'Brasil' },
    { label: 'Igreja de São Gonçalo do Amarante, Recife', country: 'Brasil' },
    { label: 'Praça do Arsenal, Recife', country: 'Brasil' },
    { label: 'Igreja de Nossa Senhora da Conceição, Olinda', country: 'Brasil' },
    { label: 'Palácio dos Governadores, Olinda', country: 'Brasil' },
    { label: 'Museu de Arte de Pernambuco, Recife', country: 'Brasil' },
    { label: 'Museu da Cidade do Recife', country: 'Brasil' },
    { label: 'Estação Central do Brasil, Recife', country: 'Brasil' },
    { label: 'Centro de Artesanato de Pernambuco, Recife', country: 'Brasil' },
    { label: 'Jardim Botânico do Recife', country: 'Brasil' },
    { label: 'Shopping Costa Azul, Paulista', country: 'Brasil' },
    { label: 'Praia de Maria Farinha, Paulista', country: 'Brasil' },
    { label: 'Caminho do Mar, Paulista', country: 'Brasil' },
    { label: 'Igreja de São Pedro, Olinda', country: 'Brasil' },
    { label: 'Museu de Arte Sacra de Pernambuco, Olinda', country: 'Brasil' },
    { label: 'Parque 13 de Maio, Recife', country: 'Brasil' },
    { label: 'Praia do Pina, Recife', country: 'Brasil' },
    { label: 'Igreja de Nossa Senhora do Carmo, Recife', country: 'Brasil' },
    { label: 'Casa da Cultura, Recife', country: 'Brasil' },
    { label: 'Parque da Jaqueira, Recife', country: 'Brasil' },
    { label: 'Estádio Ilha do Retiro, Recife', country: 'Brasil' },
    { label: 'Praça do Rosário, Recife', country: 'Brasil' },
    { label: 'Igreja de São João Batista, Olinda', country: 'Brasil' },
    { label: 'Praça do Bairro Novo, Paulista', country: 'Brasil' },
    { label: 'Catedral da Sé, Olinda', country: 'Brasil' },
    { label: 'Museu do Frevo, Recife', country: 'Brasil' },
    { label: 'Estação de BRT de Recife', country: 'Brasil' },
    { label: 'Praça da Independência, Recife', country: 'Brasil' },
    { label: 'Ponte Maurício de Nassau, Recife', country: 'Brasil' },
    { label: 'Praça do Entroncamento, Paulista', country: 'Brasil' },
    { label: 'Praia de Candeias, Recife', country: 'Brasil' },
    { label: 'Praia da Conceição, Olinda', country: 'Brasil' },
    { label: 'Praça da Liberdade, Recife', country: 'Brasil' },
    { label: 'Teatro Guararapes, Recife', country: 'Brasil' },
    { label: 'Pátio do Livramento, Olinda', country: 'Brasil' },
    { label: 'Praia do Centro, Paulista', country: 'Brasil' },
    { label: 'Parque dos Manguezais, Recife', country: 'Brasil' },
    { label: 'Museu do Carnaval, Recife', country: 'Brasil' },
    { label: 'Teatro de Santa Isabel, Recife', country: 'Brasil' },
    { label: 'Feira de São José, Recife', country: 'Brasil' },
    { label: 'Praça dos Quatro Cantos, Olinda', country: 'Brasil' },
    { label: 'Casa dos Bonecos Gigantes, Olinda', country: 'Brasil' },
    { label: 'Museu do Mar, Recife', country: 'Brasil' },
    { label: 'Parque da Avenida, Paulista', country: 'Brasil' },
  ];
  
  export default top100Locations;
  